name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - run: bun install --frozen-lockfile
      - run: bun run check
      - run: bun run check:svelte
      - run: bun test
      - run: bun run build
      - run: bun run test:static
